services:
  - type: static_site
    name: ai-fake-job-detector-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-fake-job-detector-backend.onrender.com

  - type: web_service
    name: ai-fake-job-detector-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: AI_API_URL
        value: https://ai-fake-job-detector-ai.onrender.com
      - key: FRONTEND_URL
        value: https://ai-fake-job-detector-frontend.onrender.com

  - type: web_service
    name: ai-fake-job-detector-ai
    env: python
    rootDir: ai-model
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
